# Generated by Django 3.2.11 on 2022-11-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0005_ripeirr"),
        ("extras", "0006_exporttemplate"),
    ]

    operations = []
