# Generated by Django 5.2.10 on 2026-01-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0007_merge_0005_ripeirr_0006_exporttemplate'),
        ('extras', '0021_ixapi_api_url_field'),
    ]

    operations = [
    ]
