# Generated by Django 5.2.10 on 2026-01-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0022_merge_20260107_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripeirr',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ripeirr',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
